package org.taiko.entity;
// Generated Apr 25, 2018 12:36:18 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PinKod generated by hbm2java
 */
@Entity
@Table(name = "pin_kod", schema = "public")
public class PinKod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String pin;

	public PinKod() {
	}

	public PinKod(int id, String pin) {
		this.id = id;
		this.pin = pin;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "pin", nullable = false, length = 8)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

}
